<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : protobuf.proto
 */


namespace app\Protobuf;

/**
 * Protobuf enum : youwo.CMD_METHOD
 */
class CMD_METHOD extends \Protobuf\Enum
{

    /**
     * Login = 1
     */
    const Login_VALUE = 1;

    /**
     * @var \app\Protobuf\CMD_METHOD
     */
    protected static $Login = null;

    /**
     * @param int $value
     * @return \app\Protobuf\CMD_METHOD
     */
    public static function valueOf($value)
    {
        switch ($value) {
            case 1:
                return self::Login();
            default:
                return null;
        }
    }

    /**
     * @return \app\Protobuf\CMD_METHOD
     */
    public static function Login()
    {
        if (self::$Login !== null) {
            return self::$Login;
        }

        return self::$Login = new self('Login', self::Login_VALUE);
    }
}
